language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source --dev

script:
  - ./vendor/bin/phpunit -v -c phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi