language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit -v -c phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script:
- if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/php-coveralls -v; fi
