@startuml
!ifndef dial_pu
!define dial_pu


!include styles.pu
!include indicator.pu
!include filter.pu
!include stamp.pu



package Debuggy {
	namespace Gauger {
		class Dial {
			- $_collection : Stamp[]
			- $_filter : Filter
			- $_indicator : Indicator
			+ __construct (Indicator $indicator, Filter $filter = null)
			+ stamp (string $id, mixed $extra = null) : bool
			+ idle (mixed $extra = null) : void
			+ erase (string $id) : void
			+ getCollection () : Stamp[]
			+ getFilter () : Filter
			+ getIndicator () : Indicator
		}

		Dial o-- _Indicator
		Dial o-- _Filter
		Dial o-- Stamp
	}
}

!endif
@enduml