@startuml
!ifndef sample_pu
!define sample_pu


!include styles.pu
!include gauge.pu



package Debuggy {
	namespace Gauger {
		abstract class "Sample" as _Sample {
			- $_gauge : Gauge
			+ __construct (Gauge $gauge)
			+ stamp (string $id, mixed $extra = null) : void
			+ benchmark (\Closure $subject, string $stampId, mixed $extra = null, array $arguments = [], bool $rememberResult = false) : mixed
			+ getGauge () : Gauge
			+ toString () : string
			+ {abstract} toArray () : array
			# {abstract} initGauge (Gauge $gauge) : void
		}

		_Sample --> Gauge
	}
}

!endif
@enduml