@startuml
!ifndef sample_pu
!define sample_pu


!include styles.pu
!include gauge.pu



package Debuggy {
	namespace Gauger {
		abstract class "Sample" as _Sample {
			- $_gauge : Gauge
			# __construct (Gauge $gauge)
			+ getGauge () : Gauge
			+ toString () : string
			+ {abstract} toArray () : array
		}

		_Sample --> Gauge
	}
}

!endif
@enduml